version: "3.5"

services:
  postgres-orders:
    image: postgres:15.4-alpine3.18
    container_name: postgres-orders
    restart: always
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U habrpguser -d habrdb' ]
      interval: 10s
      timeout: 30s
      retries: 10
    volumes:
      - 'postgres_orders_storage:/var/lib/postgresql/data'
    ports:
      - '127.0.0.1:5432:5432'
    env_file:
      - './postgres.env'
    networks:
      - marketplace_network
  marketplace-orders:
    container_name: marketplace-orders
    restart: always
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - '0.0.0.0:7172:7172'
    env_file:
      - './service.env'
    networks:
      - marketplace_network
# Volumes.
volumes:
  postgres_orders_storage:
    driver: local

# Networks.
networks:
  marketplace_network:
    external: true